config/routes.rb
GUT::Application.routes.draw do

  get "users/show"
  post 'share/sendEmails/:id', to: 'share#sendEmails'

  devise_for :users

  resources :usertests do
  	member do
  		post :publish
      get :test
      get :share
      get :export
  	end
  end

  resources :users
  resources :results
  resources :testpeople

  root to: "usertests#index"
end

app/models/usertest.rb
class Usertest < ActiveRecord::Base

	mount_uploader :product, ProductUploader
	belongs_to :user
	
	validates :title, presence: true,
                    length: { minimum: 5 }

    #scope :finished, where(['end_date < ?', DateTime.now])

    scope :finished, -> { where(['end_date < ?', DateTime.now]) }
    scope :published, -> { where(['status = ?', true]) }

    #scope :published, where(['status = ?', true])

   has_many :uploads
   has_many :results, dependent: :destroy
   
   accepts_nested_attributes_for :uploads

end

app/controllers/usertests_controller.rb
class UsertestsController < ApplicationController

	before_filter :authenticate_user!, :except => [:show, :check_cookie]
	before_filter :check_cookie, :only => [:show]
	before_action :set_test, :set_method_id, :set_methodname, :set_usertest_id, only: [:show, :edit, :update, :destroy, :test]
	helper_method :abtest_count, :get_methodname

	def new
		@test = Usertest.new()
		@upload = @test.uploads.build
	end

	def create
		@test = Usertest.new(test_params)
		@test.status = 0
		@test.user = current_user

		if @test.save

			if params[:uploads]
				params[:uploads]['photo'].each do |a|
					@upload = @test.uploads.create!(:photo => a, :usertest_id => @test.id)
				end
			end

			redirect_to usertests_path
		else
			render 'new'
		end
	end

	def check_cookie
		if !current_user

			if cookies.permanent.signed[:test_done] == params[:id]
				 render 'testdone'
			else
				cookies.permanent.signed[:test_done] = params[:id]
			end

		end
	end

	def show

		@test = Usertest.find(params[:id])
		@results = @test.results
		@uploads = @test.uploads

		session[:usertest_id] = params[:id]

    if !current_user && @test.end_date.strftime("%d-%m-%Y") < Date.today.strftime("%d-%m-%Y")
      render 'testrunout'
    end

	end

	def destroy
		#only able to delete if user made the test
		if current_user == @test.user
		  @test.destroy
		  redirect_to usertests_path
		else
		  redirect_to @test, notice: 'Je kunt deze test niet verwijderen.'
		end
	end

	def update
		if @test.update(test_params)
			redirect_to @test
		else
			render 'edit'
		end
	end

	def publish
		@p = Usertest.find(params[:id])
  		@p.toggle!(:status)
	end


	def index
		#@tests = Usertest.all()
		@tests = Usertest.where(nil) # creates an anonymous scope
  	@tests = @tests.finished() if params[:finished].present?
	end


	def finished
		@tests = Usertest.finished()
	end

	def edit
	  if current_user != @test.user
	  	redirect_to @test, notice: 'Je kunt deze test niet bewerken.'
	  end
	end

	def share
		@test = Usertest.find(params[:id])
	end

	def abtest_count
		abcountarray = []

		ab1 = Result.where("result -> 'abtest' = '1' AND usertest_id = ? ", params[:id]).count
		ab2 = Result.where("result -> 'abtest' = '2' AND usertest_id = ? ", params[:id]).count

		abcountarray.push(ab1, ab2)
	end


	def get_methodname(method_id)

		if method_id === 1
			@methodname = "Memory test"

		elsif method_id  === 2
			@methodname = "Blur test"

		elsif method_id  === 3
			@methodname = "Zwart wit test"

		elsif method_id  === 4
			@methodname = "AB test"

		elsif method_id  === 5
			@methodname = "Onleesbaar test"
		else
			@methodname = "Geen methode gevonden"
		end

		return @methodname
	end

private
  def set_test
    @test = Usertest.find(params[:id])
  end

  def test_params
    params.require(:usertest).permit(:title,
     																 :introtext,
     																 :outrotext,
     																 :method_id,
     																 :start_date,
																     :end_date,
																     :status,
																     :product,
																     :url,
																     :glyphoption1,
																     :glyphoption2,
																     :glyphoption3,
																     :test_time,
																     uploads_attributes: [:id,
																	      									:usertest_id,
																	      									:photo
																      										])
  end

  def set_method_id
		gon.push({
		  :method_id => @test.method_id
		})
  end

  def set_usertest_id
 		gon.push({
 		  :usertest_id => @test.id
 		})
  end

  def set_methodname

		if @test.method_id === 1
			@methodname = "Memory test"

		elsif @test.method_id  === 2
			@methodname = "Blur test"

		elsif @test.method_id  === 3
			@methodname = "Zwart wit test"

		elsif @test.method_id  === 4
			@methodname = "AB test"

		elsif @test.method_id  === 5
			@methodname = "Onleesbaar test"
		else
			@methodname = "Geen methode gevonden"
		end

	end

end

app/helpers/usertests_helper.rb
module UsertestsHelper
end

app/views/usertests/_abtest_results.html.erb
<div class="content-container">
<h1>Resultaten van de <%= @test.title %></h1>
<% if @results.count === 1 %>
	<h2><%= @results.count %> Persoon heeft de test gedaan</h2>
<% elsif @results.count > 1 %>
	<h2><%= @results.count %> Mensen hebben de test gedaan</h2>
<% end %>

	<div class="abresult_container">
		<% @uploads.each_with_index do |p, index| %>
			<div class="abresult">
			<%= image_tag p.photo_url, :class => "abChoice", :data => {:ab => index} %>
				<div class="aboverlay">
				<% if index == 0 %>
					<%= abtest_count.at(0) %>
				<% elsif index == 1 %>
					<%= abtest_count.at(1) %>
				<% end %>
				</div>
			</div>
 		<% end %>
		</div>

	<table id="results" width="100%">
		<thead>
			<tr>
				<td>Nummer</td>
				<td>Datum</td>
				<td>Browser</td>
				<td>IP</td>
				<td>Resolutie</td>
				<td>Welke vind je beter?</td>
			</tr>
		</thead>
		<tbody>
	
			 <% @results.each do |r| %>
				<% if r.testperson %>
					<tr>
						<td><%= r.testperson.id %></td>
					<td><%= r.testperson.created_at.strftime("%m/%d/%Y om %I:%M%p") %></td>
					 	<td><%= r.testperson.browser %></td>
						<td><%= r.testperson.ip %></td>
					 	<td><%= r.testperson.width %> x <%= r.testperson.height %></td>
					 	<td><%= r.result["abtest"] %></td>
					</tr>
				<% end %>
			 <% end %>
		</tbody>
	</table>

</div>

app/views/usertests/_form.html.erb
<%= simple_form_for @test, :html=> { class: 'addform' } do |f| %>

	<% if @test.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% @test.errors.full_messages.each do |msg| %>
				  <li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :titel %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label "Inleidende tekst" %>
		<%= f.text_area :introtext %>
	</p>

	<p>
		<%= f.label "Afsluitende tekst" %>
		<%= f.text_area :outrotext %>
	</p>
	<p>
		<%= f.label :testmethode %>
		<%= f.select :method_id, options_for_select([
				["Memory test", 1],
				["Blur test", 2],
				["Zwart wit test", 3],
				["Abtest", 4],
				["Onleesbaar test", 5]
			],:selected => 1) %>
	</p>

	<p>
		<%= f.input :test_time, as: :integer %>
	</p>
	<p>
		<%= f.label "Begin datum" %>
		<%= f.date_select(:start_date) %>
	</p>
	<p>
		<%= f.label "Eind datum" %>
		<%= f.date_select(:end_date) %>
	</p>

	<div class="singleImage">
		<p>
	      <%= f.label "Afbeelding" %><br>
	      <%= f.file_field :product %>
	  	</p>
  	</div>

  	<div class="multipleImages">
  		<h3> Selecteer voor een abtest twee afbeeldingen</h3>
		<%= f.fields_for :uploads do |p| %>
			<div class="field">
				<%= p.label "Afbeeldingen" %><br>
				<%= p.file_field :photo, :multiple => true, name: "uploads[photo][]" %>
			</div>
		<% end %>
  	</div>

	<div class="glyphtest">
	<h3> Onleesbaarheids test</h3>
	<p style="margin-bottom:10px; width:500px;">
	Voor de onleesbaarheids test worden extra velden verwacht, de testpersoon krijgt aan het einde van de test 3 opties voorgelegd, aan de hand van de opties kun je zien waar de gebruiker aan denkt bij het zien van jou design.
	<br/>
	</p>
			<p>
				<%= f.label "Eerste optie Onleesbaar test" %>
				<%= f.text_field :glyphoption1 %>
			</p>
			<p>
				<%= f.label "Tweede optie Onleesbaar test" %>
				<%= f.text_field :glyphoption2 %>
			</p>
			<p>
				<%= f.label "Derde optie Onleesbaar test" %>
				<%= f.text_field :glyphoption3 %>
			</p>
			<p>
		      <%= f.label "Link naar de website, zonder http://" %><br>
		      <%= f.text_field :url %>
		  	</p>
	</div>


	<p>
	<%= f.submit %>
	</p>
<% end %>

app/views/usertests/_glyphtest_results.erb
<div class="content-container">
<h1>Resultaten van de <%= @test.title %></h1>
<% if @results.count === 1 %>
	<h2><%= @results.count %> Persoon heeft de test gedaan</h2>
<% elsif @results.count > 1 %>
	<h2><%= @results.count %> Mensen hebben de test gedaan</h2>
<% end %>
	<table id="results" width="100%">
		<thead>
			<tr>
				<td>Nummer</td>
				<td>Datum</td>
				<td>Browser</td>
				<td>IP</td>
				<td>Resolutie</td>
				<td>Wat viel je het als eerst op?</td>
				<td>Wat heb je onthouden?</td>
			</tr>
		</thead>
		<tbody>
	
			 <% @results.each do |r| %>
				<% if r.testperson %>
					<tr>
						<td><%= r.testperson.id %></td>
					<td><%= r.testperson.created_at.strftime("%m/%d/%Y om %I:%M%p") %></td>
					 	<td><%= r.testperson.browser %></td>
						<td><%= r.testperson.ip %></td>
					 	<td><%= r.testperson.width %> x <%= r.testperson.height %></td>
					 	<td><%= r.result["q1"] %></td>
					 	<td><%= r.result["glyphoptions"] %></td>
					</tr>
				<% end %>
			 <% end %>
		</tbody>
	</table>
</div>

app/views/usertests/_grayscale.html.erb
<%= include_gon %>
<%= javascript_include_tag "methods.js" %>

<header>
    <div class="user">
        <div class="username">
            Deze test is gemaakt door:
            <span><%= @test.user.email %></span>
        </div>
    </div>

    <h3><%= @test.title %></h3>
</header>

    <% if @test.test_time %>
        <div id="timer" data-time="<%= @test.test_time %>"></div>
    <% else %>
        <div id="timer" data-time="3"></div>
    <% end %>

<div id="test">
	
    <div class="step" data-step="1">
        <h2>Stap 1</h2>
        <%= @test.introtext %>
        <p>Je hebt 10 seconden om de volgende afbeelding in je op te nemen.</p>

        <button class="btn nextButton">Begin met test</button>
    </div>

    <div class="step" data-step="2">
            <div class="abcontainer">
                <%= image_tag @test.product.url(:gray) %>
            </div>
    </div>

    <div class="step" data-step="3">
        <h2>Stap 3</h2>
        
        <%= simple_form_for :result, :url => {:action => :create, :controller => "results"} do |f| %>
            
            <%= f.label "Waar denk je dat deze afbeelding voor dient?" %>
            <%= f.text_area :q1 %>
            <%= f.input :testperson_id, :as => :hidden, :input_html => { :value => "" } %>

            <%= f.submit "Opslaan" %>
        <% end %> 

    </div>
 
</div>

app/views/usertests/_memory.html.erb
<%= include_gon %>
<%= javascript_include_tag "methods.js" %>

<header>
    <div class="user">
        <div class="username">
            Deze test is gemaakt door:
            <span><%= @test.user.email %></span>
        </div>
    </div>

    <h3><%= @test.title %></h3>
</header>

<% if @test.test_time %>
    <div id="timer" data-time="<%= @test.test_time %>"></div>
<% else %>
    <div id="timer" data-time="3"></div>
<% end %>

<div id="test">
     <div class="step" data-step="1">
        <h2>Stap 1</h2>
        <p><%= @test.introtext %></p>
        <p>Er komt in een flits een afbeelding voorbij, probeer zoveel mogelijk te onthouden</p>

        <button class="btn nextButton">Begin met test</button>
    </div>

    <div class="step" data-step="2">
        <h2>Stap 2</h2>
        <%= image_tag(@test.product) %>
    </div>

    <div class="step" data-step="3">
        <h2>Stap 3</h2>
        
        <%= simple_form_for :result, :url => {:action => :create, :controller => "results"} do |f| %>
            
            <%= f.label "Wat viel je het als eerst op?" %>
            <%= f.text_area :q1 %>

            <%= f.label "Wat heb je onthouden?" %>
            <%= f.text_area :q2 %>

            <%= f.input :testperson_id, :as => :hidden, :input_html => { :value => "" } %>
            <%= f.submit "Opslaan" %>
        <% end %> 

    </div>

</div>

app/views/usertests/_memory_results.html.erb
<div class="content-container">
<h1>Resultaten van de <%= @test.title %></h1>
<% if @results.count === 1 %>
	<h2><%= @results.count %> Persoon heeft de test gedaan</h2>
<% elsif @results.count > 1 %>
	<h2><%= @results.count %> Mensen hebben de test gedaan</h2>
<% end %>
	<table id="results" width="100%">
		<thead>
			<tr>
				<td>Nummer</td>
				<td>Datum</td>
				<td>Browser</td>
				<td>IP</td>
				<td>Resolutie</td>
				<td>Wat viel je het als eerst op?</td>
				<td>Wat heb je onthouden?</td>
			</tr>
		</thead>
		<tbody>
	
			 <% @results.each do |r| %>

				<% if r.testperson %>
					<tr>
						<td><%= r.testperson.id %></td>
					<td><%= r.testperson.created_at.strftime("%m/%d/%Y om %I:%M%p") %></td>

					 	<td><%= r.testperson.browser %></td>
						<td><%= r.testperson.ip %></td>
					 	<td><%= r.testperson.width %> x <%= r.testperson.height %></td>
					 	<td><%= r.result["q1"] %></td>
					 	<td><%= r.result["q2"] %></td>
					</tr>
				<% end %>
			 <% end %>
		</tbody>
	</table>
</div>

app/views/usertests/edit.html.erb
<div class="content-container">
	<div class="content-header">
		<h1>Bewerken van: <%= @test.title %></h1>
	</div>

	<%= render 'form' %>
</div>

app/views/usertests/index.html.erb
<div class="content-container">
<%= link_to "Nieuwe test toevoegen", new_usertest_path, class: "btn_create" %>
 	<% @tests.each do |t| %>
		<div class="test">
			<div class="test-header">
				<h2><%= t.title %></h2>
				<h4><%= get_methodname(t.method_id) %></h4>
				<% if current_user.id == t.user_id %>
				<div class="actions">
					<%= link_to "Delen", share_usertest_path(t) %>
			    	<%= link_to "Resultaten bekijken", usertest_path(t) %>
			    	<%= link_to 'Verwijderen', usertest_path(t), method: :delete, data: { confirm: 'Weet je het zeker?' } %>
		    	</div>
		    <% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/usertests/new.html.erb
<div class="content-container">
<h1>Nieuwe test aanmaken</h1>
<%= render 'form' %>
</div>

app/views/usertests/share.html.erb
<div class="content-container">
<h1><%= @test.title %> Delen</h1>

<h2> Kopieer en plak de link </h2>

<div class="copypasterino">
  <input type="text" value="<%= usertest_url(@test) %>"/>
</div>

<h2>Deel via social media</h2>
       <ul class="rrssb-buttons clearfix">
                    <li class="email">
                        <!-- Replace subject with your message using URL Endocding: http://meyerweb.com/eric/tools/dencoder/ -->
                        <a href='mailto:?subject=Doe mee aan mijn test!&body=<%= usertest_url(@test) %>' target="_blank">
                            <span class="icon">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve"><g><path d="M20.111 26.147c-2.336 1.051-4.361 1.401-7.125 1.401c-6.462 0-12.146-4.633-12.146-12.265 c0-7.94 5.762-14.833 14.561-14.833c6.853 0 11.8 4.7 11.8 11.252c0 5.684-3.194 9.265-7.399 9.3 c-1.829 0-3.153-0.934-3.347-2.997h-0.077c-1.208 1.986-2.96 2.997-5.023 2.997c-2.532 0-4.361-1.868-4.361-5.062 c0-4.749 3.504-9.071 9.111-9.071c1.713 0 3.7 0.4 4.6 0.973l-1.169 7.203c-0.388 2.298-0.116 3.3 1 3.4 c1.673 0 3.773-2.102 3.773-6.58c0-5.061-3.27-8.994-9.303-8.994c-5.957 0-11.175 4.673-11.175 12.1 c0 6.5 4.2 10.2 10 10.201c1.986 0 4.089-0.43 5.646-1.245L20.111 26.147z M16.646 10.1 c-0.311-0.078-0.701-0.155-1.207-0.155c-2.571 0-4.595 2.53-4.595 5.529c0 1.5 0.7 2.4 1.9 2.4 c1.441 0 2.959-1.828 3.311-4.087L16.646 10.068z"/></g></svg>
                            </span>
                            <span class="text">email</span>
                        </a>
                    </li>
                    <li class="facebook">
                        <!-- Replace with your URL. For best results, make sure you page has the proper FB Open Graph tags in header:
                        https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content/ -->
                        <a href='https://www.facebook.com/sharer/sharer.php?u=<%= usertest_url(@test) %>' class="popup" target="_blank">
                            <span class="icon">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                                    <path d="M27.825,4.783c0-2.427-2.182-4.608-4.608-4.608H4.783c-2.422,0-4.608,2.182-4.608,4.608v18.434
                                        c0,2.427,2.181,4.608,4.608,4.608H14V17.379h-3.379v-4.608H14v-1.795c0-3.089,2.335-5.885,5.192-5.885h3.718v4.608h-3.726
                                        c-0.408,0-0.884,0.492-0.884,1.236v1.836h4.609v4.608h-4.609v10.446h4.916c2.422,0,4.608-2.188,4.608-4.608V4.783z"/>
                                </svg>
                            </span>
                            <span class="text">facebook</span>
                        </a>
                    </li>

                    <li class="twitter">
                        <!-- Replace href with your Meta and URL information  -->
                        <a href="http://twitter.com/home?status=Doe mee aan mijn test <%= usertest_url(@test) %>" class="popup" target="_blank">
                            <span class="icon">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                                <path d="M24.253,8.756C24.689,17.08,18.297,24.182,9.97,24.62c-3.122,0.162-6.219-0.646-8.861-2.32
                                    c2.703,0.179,5.376-0.648,7.508-2.321c-2.072-0.247-3.818-1.661-4.489-3.638c0.801,0.128,1.62,0.076,2.399-0.155
                                    C4.045,15.72,2.215,13.6,2.115,11.077c0.688,0.275,1.426,0.407,2.168,0.386c-2.135-1.65-2.729-4.621-1.394-6.965
                                    C5.575,7.816,9.54,9.84,13.803,10.071c-0.842-2.739,0.694-5.64,3.434-6.482c2.018-0.623,4.212,0.044,5.546,1.683
                                    c1.186-0.213,2.318-0.662,3.329-1.317c-0.385,1.256-1.247,2.312-2.399,2.942c1.048-0.106,2.069-0.394,3.019-0.851
                                    C26.275,7.229,25.39,8.196,24.253,8.756z"/>
                                </svg>
                           </span>
                            <span class="text">twitter</span>
                        </a>
                    </li>

                    <li class="googleplus">
                        <!-- Replace href with your meta and URL information.  -->
                        <a href="https://plus.google.com/share?url=<%= usertest_url(@test) %>" class="popup" target="_blank">
                            <span class="icon">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                                    <g>
                                        <g>
                                            <path d="M14.703,15.854l-1.219-0.948c-0.372-0.308-0.88-0.715-0.88-1.459c0-0.748,0.508-1.223,0.95-1.663
                                                c1.42-1.119,2.839-2.309,2.839-4.817c0-2.58-1.621-3.937-2.399-4.581h2.097l2.202-1.383h-6.67c-1.83,0-4.467,0.433-6.398,2.027
                                                C3.768,4.287,3.059,6.018,3.059,7.576c0,2.634,2.022,5.328,5.604,5.328c0.339,0,0.71-0.033,1.083-0.068
                                                c-0.167,0.408-0.336,0.748-0.336,1.324c0,1.04,0.551,1.685,1.011,2.297c-1.524,0.104-4.37,0.273-6.467,1.562
                                                c-1.998,1.188-2.605,2.916-2.605,4.137c0,2.512,2.358,4.84,7.289,4.84c5.822,0,8.904-3.223,8.904-6.41
                                                c0.008-2.327-1.359-3.489-2.829-4.731H14.703z M10.269,11.951c-2.912,0-4.231-3.765-4.231-6.037c0-0.884,0.168-1.797,0.744-2.511
                                                c0.543-0.679,1.489-1.12,2.372-1.12c2.807,0,4.256,3.798,4.256,6.242c0,0.612-0.067,1.694-0.845,2.478
                                                c-0.537,0.55-1.438,0.948-2.295,0.951V11.951z M10.302,25.609c-3.621,0-5.957-1.732-5.957-4.142c0-2.408,2.165-3.223,2.911-3.492
                                                c1.421-0.479,3.25-0.545,3.555-0.545c0.338,0,0.52,0,0.766,0.034c2.574,1.838,3.706,2.757,3.706,4.479
                                                c-0.002,2.073-1.736,3.665-4.982,3.649L10.302,25.609z"/>
                                            <polygon points="23.254,11.89 23.254,8.521 21.569,8.521 21.569,11.89 18.202,11.89 18.202,13.604 21.569,13.604 21.569,17.004
                                                23.254,17.004 23.254,13.604 26.653,13.604 26.653,11.89      "/>
                                        </g>
                                    </g>
                                </svg>
                            </span>
                            <span class="text">google+</span>
                        </a>
                    </li>
                </ul>
            </div>

app/views/usertests/show.html.erb
<% if !current_user %>
	<% if @test.method_id === 1 %>
		<%= render 'memory' %>
	<% elsif @test.method_id === 2 %>
	    <%= render 'blur' %>
    <% elsif @test.method_id === 3 %>
	    <%= render 'grayscale' %>
	<% elsif @test.method_id === 4 %>
	  <%= render 'abtest' %>
	<% elsif @test.method_id === 5 %>
	  <%= render 'glyphtest' %>
	<% end %>
<% else %>

	<% if @results.count > 0 %>
		<% if @test.method_id === 1 || @test.method_id === 2 %>
			<%= render 'memory_results' %>
		<% elsif @test.method_id === 3 %>
		  <%= render 'grayscale_results' %>
		<% elsif @test.method_id === 4 %>
		  <%= render 'abtest_results' %>
		<% elsif @test.method_id === 5 %>
		  <%= render 'glyphtest_results' %>
		<% end %>
	<% else %>
		<div class="content-container">
			<h1> Er zijn nog geen resultaten </h1>
		</div>
	<% end %>

<% end %>

app/views/usertests/test.html.erb
<div class="content-container">
<h1>Test uitvoeren:
<%=  @test.title %> </h1>
<p><%= @test.introtext %></p> 

<%= link_to "Test uitvoeren beëindigen", usertests_path(), confirm: 'Weet je zeker dat je de test wilt verlaten?' %>
</div>

app/views/usertests/testdone.html.erb
<div class="login">
<div class="login-header">
    <div class="logo">
      <label>GUT</label>
    </div>
  </div>
  <br/>
  <h1> Sorry, </h1>
  <h2>Jij hebt deze test al gedaan!</h2>
</div>

app/views/usertests/testrunout.html.erb
<div class="login">
  <div class="login-header">
      <div class="logo">
        <label>GUT</label>
      </div>
  </div>
  <br/>
  <h1> Sorry, </h1>
  <h2>De testperiode is helaas afgelopen</h2>
</div>