config/routes.rb
GUT::Application.routes.draw do

  get "users/show"
  post 'share/sendEmails/:id', to: 'share#sendEmails'

  devise_for :users

  resources :usertests do
  	member do
  		post :publish
      get :test
      get :share
      get :export
  	end
  end

  resources :users
  resources :results
  resources :testpeople

  root to: "usertests#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GUT</title>
  <%= include_gon(:init => true) %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


    <% if user_signed_in? %>

    <div id="header">
      <div class="logo">
        <label>GUT</label>
      </div>
      <div class="userdata">
        <div class="userinfo">
          <% if user_signed_in? %>
           <%= image_tag avatar_url(current_user, 50), :class => "avatar" %>
            <span class="name"><%= current_user.email %></span> <br/>
          <%= link_to 'Profiel', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Uitloggen", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Registreren", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Inloggen", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </div>  
    </div>

    <% end %>
    
    <% if user_signed_in? %>
      <div class="sidebar">
        <div class="menu">
        
          <%= nav_link root_path do %>
              <span><i class="dashboard_icon"></i>Dashboard</span>
          <% end %>
    
          <%= nav_link usertests_path do %>
              <span><i class="finished_icon"></i>Gepubliceerde testen</span>
          <% end %>

          <%= nav_link usertests_path(:finished => "true") do %>
              <span><i class="tips_icon"></i>Afgeronde testen</span>
          <% end %>

        </div>
      </div>
    <% end %>
    
    <%= yield %>

</body>
</html>